- name: include password
  include_vars: password.yml

- name: display password
  debug: msg="Password is {{ mysql_root_password }}"

- name: ensure apache is installed
  apt: pkg=apache2 update_cache=yes state=installed 
