# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configure some parameters here:

$parameters = {
  "project"   => "vagrant-vm",
  "memory"    => 2048,
  "cpus"      => 1,
  "provision_shell" => "../../../provision.sh",  
  "vagrant_box" => "debian/wheezy64",
  "ansible_host_file" => "vagrant.hosts",
  "ansible_playbook" => "site.yml",
  "roles_dir" => "../../roles", # optional: remove key if you do not use an external `roles` directory
}

require '../common/ansible_provisionner'